### ISSUE TITLE
Unable to rearrange favorite subbreddits on bar

### ISSUE THREAD

**Issue by ghost** [bermudalocket/Tweaks-for-Reddit#42] opened 2021-07-05 16:46 UTC
- I added a bunch of subreddits in alphabetical order, something happened and on refresh the bar is out of the order I put it in.
- Tried to delete the favorites but, the window closes w/o removing the favorite
- Attempted to reinstall tweaks for reddit, but I guess this pulls into cloud kit.
- Any chance for an ability to sort the favorites in alphabetical order?

Apologies I think this is 3 separate issues.

**Comment by bermudalocket** [comment] 2021-07-05 16:58
> Tried to delete the favorites but, the window closes w/o removing the favorite

I've reproduced this. It looks like a system-level crash. I was actually getting this when I was working on the latest release, but I was only able to reproduce it on the macOS Monetery beta and not on Big Sur. Can you confirm you're running Big Sur?

I'll have to explore an alternative way to present actions on favorite subreddits.

Monterey crash log:
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   AppKit                        	    0x7ff819d849de -[NSApplication _crashOnException:] + 313
1   AppKit                        	    0x7ff819d8470f -[NSApplication reportException:] + 731
2   AppKit                        	    0x7ff819e2de0f uncaughtErrorProc + 145
3   HIToolbox                     	    0x7ff81fb8f289 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 2075
4   HIToolbox                     	    0x7ff81fb8e40e SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 333
5   HIToolbox                     	    0x7ff81fba355b SendEventToEventTarget + 39
6   HIToolbox                     	    0x7ff81fc03eef SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 365
7   HIToolbox                     	    0x7ff81fc2937e SendMenuCommandWithContextAndModifiers + 46
8   HIToolbox                     	    0x7ff81fc29328 SendMenuItemSelectedEvent + 348
9   HIToolbox                     	    0x7ff81fc2917a FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 96
10  HIToolbox                     	    0x7ff81fd358ac PopUpMenuSelectCore(MenuData*, Point, double, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, unsigned int, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*) + 1450
11  HIToolbox                     	    0x7ff81fd34e20 _HandlePopUpMenuSelection8(OpaqueMenuRef*, OpaqueEventRef*, unsigned int, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*) + 410
12  HIToolbox                     	    0x7ff81fc0bb1d _HandlePopUpMenuSelectionWithDictionary + 329
13  AppKit                        	    0x7ff819e9d850 SLMPerformPopUpCarbonMenu + 2232
14  AppKit                        	    0x7ff819d44631 _NSSLMPopUpCarbonMenu3 + 1125
15  AppKit                        	    0x7ff819d44126 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 462
16  AppKit                        	    0x7ff819d78ae2 -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 562
17  AppKit                        	    0x7ff819c062ec -[NSControl mouseDown:] + 678

```

**Comment by bermudalocket** [comment] 2021-07-05 16:59
To answer your other questions:
> Attempted to reinstall tweaks for reddit, but I guess this pulls into cloud kit.

Yeah, almost everything is stored in iCloud now so uninstalling will not wipe your data.

> Any chance for an ability to sort the favorites in alphabetical order?

Sure, I'll look into this.

**Comment by linuxpng** [comment] 2021-07-05 17:05
Thanks for the replies.  This is on Big Sur 11.4,  m1 arch if that is relevant.

**Comment by bermudalocket** [comment] 2021-07-06 16:33
Deleting favorite subs has been fixed in 1.13.1 which should be available on the App Store now :)

**Comment by linuxpng** [comment] 2021-07-06 16:38
Tested and it works correctly.  Thank you!

**Comment by linuxpng** [comment] 2021-07-06 16:39
One thing that I tested and refreshed and seemed ok, and just went back to double check.  When I add favorites, I add them in a specific (alphabetical) order.  They are getting jumbled after readding the favorite subreddits.

**Comment by bermudalocket** [comment] 2021-07-06 17:04
> One thing that I tested and refreshed and seemed ok, and just went back to double check. When I add favorites, I add them in a specific (alphabetical) order. They are getting jumbled after readding the favorite subreddits.

Oh that's odd, it's not preserving alphabetical order? What happens if you try to drag a favorite subreddit to reorder it? It's kind of a pain in the butt, but if you click the blank area to the left of the subreddit icon and drag, it'll move like a native list.

**Comment by linuxpng** [comment] 2021-07-06 17:09
I think I understand what you're asking me to do.  I get the underline like I am reordering (like bookmarks in Safari).  Unfortunately they do not move.

**Comment by bermudalocket** [comment] 2021-08-20 17:24
(Finally) added in 1.13.2.

**Closed by bermudalocket** 2021-08-20 17:24 UTC
Labels: enhancement
