### ISSUE TITLE
Paid for In-App Purchase, but cannot enable "Live preview comments in markdown"

### ISSUE THREAD

**Issue by Fofer** [bermudalocket/Tweaks-for-Reddit#22] opened 2021-05-18 02:19 UTC
Hi, I am running Safari 14.0.3 on an M1 MacBook Pro with Big Sur  11.2.3.

I previously had an older version of the github version of redditweaks installed, but today I bought Tweaks for Reddit from the Mac App Store in order to update it.   I promptly paid the $0.99 for the In-App Purchase.  But when I try to click the checkbox it just launches the app. I click on "Restore Purchases" and it says "Thank you for your support" but it still won't leave me check that box or enable "Live preview comments in markdown."  What am I missing?

**Comment by bermudalocket** [comment] 2021-05-18 17:44
Yikes, sorry about that! I've confirmed this is a bug and I am able to reproduce it. I'm very surprised this slipped by the App Store reviewer.

A fix will be in the next update (which should hopefully be approved and released within the next few hours). Thanks for reporting this!

**Comment by Fofer** [comment] 2021-05-19 13:47
You're welcome, and thanks for the quick reply!  

I just updated the app, and tried again, but unfortunately I'm still unable to enable this feature.  Here's a screen recording:  http://i.imgur.com/xt4UWZe.gif

**Comment by bermudalocket** [comment] 2021-05-19 15:26
> You're welcome, and thanks for the quick reply!  
> 
> 
> 
> I just updated the app, and tried again, but unfortunately I'm still unable to enable this feature.  Here's a screen recording:  http://i.imgur.com/xt4UWZe.gif

Hmmm. If you open the main app and select Debug in the sidebar, could you take a screenshot?

**Comment by Fofer** [comment] 2021-05-19 17:22
Sure thing:

http://i.imgur.com/13MVChZ.png

**Comment by bermudalocket** [comment] 2021-05-19 17:41
> Sure thing:
> 
> http://i.imgur.com/13MVChZ.png

Hm, ok. The app knows you made the purchase since 1) it says "Yes" on the Debug view, and 2) it says "Thanks for your support!" on the IAP view. That's good. But clearly there's a disconnect with Safari. Have you restarted Safari since updating Tweaks for Reddit? The popover is supposed to pull changes from iCloud every time it's opened, but there could be some Safari weirdness going on.

Thanks for helping me debug this. This is the first time I've ever offered an in-app purchase and there's clearly a bit of a learning curve :)

**Comment by Fofer** [comment] 2021-05-19 19:55
No problem, happy to help!  I tried restarting Safari after updating TfR.  I also tried restarting the whole Mac.  Same results, the app shows I have paid for IAP, but the checkbox for the live preview feature doesn't stay checked, it just opens the TfR app.  Anything else I can try?

**Comment by bermudalocket** [comment] 2021-05-19 23:36
> No problem, happy to help! I tried restarting Safari after updating TfR. I also tried restarting the whole Mac. Same results, the app shows I have paid for IAP, but the checkbox for the live preview feature doesn't stay checked, it just opens the TfR app. Anything else I can try?

Yeah, one last idea before I dig into the code:
1. Close Safari
2. Drag and drop the `Tweaks for Reddit.app` file in your Applications folder to the trash
3. Empty your trash to completely remove the app
4. Confirm the app has been removed by opening Safari, opening Preferences, and checking to make sure Tweaks for Reddit doesn't appear in the extensions list
5. Close Safari
6. Reinstall the app from the Mac App Store
7. Launch the main app
8. Restore purchases
9. Launch Safari
10. Try enabling the in-app purchase from the popover

**Comment by Fofer** [comment] 2021-05-20 05:12
OK, I tried that, and it still didn't work.  Same "unable to check the box" behavior even though my purchase of the IAP is already restored and confirmed.

I tried it again, using a utility called "Remove-It" to delete any preferences or other leftover files related to this app:

![CleanShot 2021-05-19 at 22 05 05](https://user-images.githubusercontent.com/518749/118922640-3de45200-b8ef-11eb-94f9-b507d78f2662.png)

Unfortunately even after a fresh re-install of the Tweaks for Reddit app, it still didn't work.

**Comment by bermudalocket** [comment] 2021-05-20 22:26
@Fofer just wanted to let you know I've been working on this today. I'm rewriting the `IAPHelper` class by wrapping all of the "delegate Hell" in publishers which, in my opinion, are much easier to handle and reason about. Shouldn't take long.

**Closed** 2021-05-22 18:05 UTC
Labels: bug

**Comment by bermudalocket** [comment] 2021-05-22 18:37
Okay, I've got this fixed. I'm going to blame it on misunderstanding how iCloud containers work with app groups within the sandbox. The current solution isn't the best for me but on the user's end it's perfectly secure. At some point in the future I'll spin up a web server so I can leverage true App Store receipt validation. We'll see when inspiration strikes.

**Comment by Fofer** [comment] 2021-05-22 18:39
Great, thanks.  Looking forward to checking it out.

Awesome work on this BTW, it's very much appreciated.

**Comment by bermudalocket** [comment] 2021-05-24 21:04
> Great, thanks. Looking forward to checking it out.
> 
> Awesome work on this BTW, it's very much appreciated.

Just checking in to see if you've had a chance to update to 1.11.1 and try out the IAP?

**Comment by Fofer** [comment] 2021-05-24 21:14
Yes, I updated and it’s working now! Thanks again! This is great work.

**Comment by bermudalocket** [comment] 2021-05-25 01:26
> Yes, I updated and it’s working now! Thanks again! This is great work.

Awesome, and thanks!
